name: Build - macOS

on:
  workflow_call:
    inputs:
      NIGHTLY:
        default: false
        type: boolean

jobs:
  build:
    name: ${{ matrix.os }} - SQLCipher ${{ matrix.sqlcipher }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        sqlcipher: ["0", "1"]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Uninstall Mono, which is included by default in GitHub-hosted macOS runners,
      # as it interferes with referencing our own compiled SQLite libraries.
      - name: Uninstall Mono
        run: |
          sudo rm -rfv /Library/Frameworks/Mono.framework
          sudo pkgutil --forget com.xamarin.mono-MDK.pkg
          sudo rm /etc/paths.d/mono-commands

      - name: Install dependencies
        run: |
          brew update
          brew tap sqlitebrowser/tap
          brew unlink openssl@3
          brew install sqlb-openssl@3
          brew install sqlb-qt@5 sqlb-sqlcipher sqlb-sqlite ninja
          npm install -g appdmg

      - name: Configure build
        run: |
          if [ "${{ inputs.NIGHTLY }}" = "true" ]; then
            if [ "${{ matrix.sqlcipher }}" = "1" ]; then
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLCipher Nightly"/' CMakeLists.txt
            else
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLite Nightly"/' CMakeLists.txt
            fi
          else
            if [ "${{ matrix.sqlcipher }}" = "1" ]; then
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLCipher-dev-'$(git rev-parse --short --verify HEAD)'"/' CMakeLists.txt
            else
                sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLite-dev-'$(git rev-parse --short --verify HEAD)'"/' CMakeLists.txt
            fi
          fi

          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DcustomTap=1 -DENABLE_TESTING=ON -Dsqlcipher=${{ matrix.sqlcipher }} ..

      - name: Build
        working-directory: ./build
        run: ninja

      - name: Tests
        working-directory: ./build
        run: ninja test

      - name: Build Extension
        run: clang -I /opt/homebrew/opt/sqlb-sqlite/include -L /opt/homebrew/opt/sqlb-sqlite/lib -fno-common -dynamiclib src/extensions/extension-formats.c
